CREATE DATABASE IF NOT EXISTS vensimWebgp3;
USE vensimWebgp3; 

CREATE TABLE IF NOT EXISTS model(
  idModel INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(500) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS diagramaForrester(
  idForrester INT PRIMARY KEY AUTO_INCREMENT,
  idModel INT NOT NULL,
  idArchivo VARCHAR(500),
  FOREIGN KEY (idModel) REFERENCES model(idModel) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS diagramaCausal(
  idCausal INT PRIMARY KEY AUTO_INCREMENT,
  idModel INT NOT NULL,
  idArchivo VARCHAR(500),
  FOREIGN KEY (idModel) REFERENCES model(idModel) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS variableCausal (
  idVariableCausal INT PRIMARY KEY AUTO_INCREMENT,
  idCausal INT NOT NULL,
  nombre VARCHAR(200),
  titulo VARCHAR(200),
  unidad VARCHAR(100),
  x_pos INT,
  y_pos INT,
  FOREIGN KEY (idCausal) REFERENCES diagramaCausal (idCausal) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ConexionCausal (
  idConexionCausal INT PRIMARY KEY AUTO_INCREMENT,
  idCausal INT NOT NULL,
  idOrigen INT NOT NULL,
  idDestino INT NOT NULL,
  polaridad VARCHAR (100),
  color VARCHAR (100),
  x_curve REAL,
  y_curve REAL,
  FOREIGN KEY (idCausal) REFERENCES diagramaCausal (idCausal) ON DELETE CASCADE,
  FOREIGN KEY (idOrigen) REFERENCES variableCausal (idVariableCausal),
  FOREIGN KEY (idDestino) REFERENCES variableCausal (idVariableCausal)
);

CREATE TABLE IF NOT EXISTS SubModel (
  idSubmodel INT PRIMARY KEY,
  idForrester INT NOT NULL,
  nombre VARCHAR (500),
  UNIQUE (idForrester, nombre),
  FOREIGN KEY (idForrester) REFERENCES diagramaForrester (idForrester) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS variableForrester (
  idVariableForrester INT PRIMARY KEY AUTO_INCREMENT,
  idSubmodel INT NOT NULL,
  nombre VARCHAR(200),
  titulo VARCHAR(200),
  tipo VARCHAR(100),
  unidad VARCHAR(100),
  tiempo VARCHAR(100),
  x_pos REAL,
  y_pos REAL,
  FOREIGN KEY (idSubmodel) REFERENCES SubModel (idSubmodel) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ConexionForrester (
  idConexionForrester INT PRIMARY KEY AUTO_INCREMENT,
  idForrester INT NOT NULL,
  idOrigen INT NOT NULL,
  idDestino INT NOT NULL,
  x_curve REAL,
  y_curve REAL,
  FOREIGN KEY (idForrester) REFERENCES diagramaForrester (idForrester) ON DELETE CASCADE,
  FOREIGN KEY (idOrigen) REFERENCES variableForrester (idVariableForrester) ON DELETE CASCADE,
  FOREIGN KEY (idDestino) REFERENCES variableForrester (idVariableForrester) ON DELETE CASCADE
);



INSERT IGNORE INTO model (idModel, nameModel) VALUES
(1,'Frecuencia de mantenimiento'),
(2,'Satisfaccion de autoridades'),
(3,'Satisfaccion de usuario'),
(4,'Seguridad vial'),
(5,'Eficiencia de movilidad');

INSERT IGNORE INTO diagramaForrester (idForrester, idModel, idArchivo) VALUES
(1,1,'frecuencia-de-mantenimiento-forrester.mdl'),
(2,2,'satisfaccion_autoridades-forrester.mdl'),
(3,3,'satisfaccion-usuario-forrester.mdl'),
(4,4,'seguridad-vial-forrester.mdl'),
(5,5,'eficiencia-de-movilidad-forrester.mdl');

INSERT IGNORE INTO diagramaCausal (idCausal, idModel, idArchivo) VALUES
(1,1,'frecuencia-de-mantenimiento-causal.mdl'),
(2,2,'satisfacción-de-autoridades-causal.mdl'),
(3,3,'satisfaccion-usuario-causal.mdl'),
(4,4,'seguridad-vial-causal.mdl'),
(5,5,'eficiencia-movilidad-causal.mdl');

INSERT IGNORE INTO variableCausal (idVariableCausal, idCausal, nombre, titulo, unidad, x_pos, y_pos  ) VALUES
(1, 1, 'Cantidad de paradas del vehiculo', 'Cantidad de paradas del vehiculo', '',0,0),
(2, 1, 'Cantidad de vehiculos en operacion', 'Cantidad de vehiculos en operacion', '',0,0),
(3, 1, 'Capacitacion del personal de mantenimiento', 'Capacitacion del personal de mantenimiento', '',0,0),
(4, 1, 'Componentes Desgastados', 'Componentes Desgastados', '',0,0),
(5, 1, 'Contaminación de la ruta', 'Contaminación de la ruta', '',0,0),
(6, 1, 'Cumplimiento del servicio', 'Cumplimiento del servicio', '',0,0),
(7, 1, 'Disponibilidad de la flota', 'Disponibilidad de la flota', '',0,0),
(8, 1, 'Disponibilidad de Repuestos', 'Disponibilidad de Repuestos', '',0,0),
(9, 1, 'Disponibilidad de Talleres', 'Disponibilidad de Talleres', '',0,0),
(10, 1, 'Frecuencia de Fallas Mecánicas', 'Frecuencia de Fallas Mecánicas', '',0,0),
(11, 1, 'Frecuencia de Interrupciones del servicio', 'Frecuencia de Interrupciones del servicio', '',0,0),
(12, 1, 'Frecuencia de Mantenimiento', 'Frecuencia de Mantenimiento', '',0,0),
(13, 1, 'Frecuencia de Mantenimiento Preventivo', 'Frecuencia de Mantenimiento Preventivo', '',0,0),
(14, 1, 'Frecuencia de uso de vehiculos', 'Frecuencia de uso de vehiculos', '',0,0),
(15, 1, 'Inactividad de Vehiculos', 'Inactividad de Vehiculos', '',0,0),
(16, 1, 'Km recorridos por vehiculos', 'Km recorridos por vehiculos', '',0,0),
(17, 1, 'Malas condiciones de via', 'Malas condiciones de via', '',0,0),
(18, 1, 'Numero de Tecnicos Disponibles', 'Numero de Tecnicos Disponibles', '',0,0),
(19, 1, 'Pasajeros por dìa', 'Pasajeros por dìa', '',0,0),
(20, 1, 'Politicas de seguridad vial', 'Politicas de seguridad vial', '',0,0),
(21, 1, 'Presupuesto asignado a mantenimiento', 'Presupuesto asignado a mantenimiento', '',0,0),
(22, 1, 'Satisfaccion del Usuario', 'Satisfaccion del Usuario', '',0,0),
(23, 1, 'Tiempo de Reparacion', 'Tiempo de Reparacion', '',0,0),
(24, 1, 'Velocidad promedio de vehiculos', 'Velocidad promedio de vehiculos', '',0,0),
(25, 1, 'Vida Util de los Componentes', 'Vida Util de los Componentes', '',0,0),
(26, 2, 'Accidentes de transito', 'Accidentes de transito', '',0,0),
(27, 2, 'Calidad de fiscalización de obras públicas', 'Calidad de fiscalización de obras públicas', '',0,0),
(28, 2, 'Calidad de infraestructura vial', 'Calidad de infraestructura vial', '',0,0),
(29, 2, 'Confianza pública', 'Confianza pública', '',0,0),
(30, 2, 'Congestión vehicular', 'Congestión vehicular', '',0,0),
(31, 2, 'Fiscalización de obras públicas', 'Fiscalización de obras públicas', '',0,0),
(32, 2, 'Fluidez del tráfico', 'Fluidez del tráfico', '',0,0),
(33, 2, 'Imagen pública de las autoridades', 'Imagen pública de las autoridades', '',0,0),
(34, 2, 'Infracciones vehiculares', 'Infracciones vehiculares', '',0,0),
(35, 2, 'Inversion en infraestructura', 'Inversion en infraestructura', '',0,0),
(36, 2, 'Pagos de tributos por transporte público', 'Pagos de tributos por transporte público', '',0,0),
(37, 2, 'Quejas de usuarios', 'Quejas de usuarios', '',0,0),
(38, 2, 'Recaudación por municipalidad', 'Recaudación por municipalidad', '',0,0),
(39, 2, 'Satisfacción de las autoridades de transporte', 'Satisfacción de las autoridades de transporte', '',0,0),
(40, 2, 'Satisfacción de los usuarios', 'Satisfacción de los usuarios', '',0,0),
(41, 2, 'Tasa de accidentes de transito', 'Tasa de accidentes de transito', '',0,0),
(42, 2, 'Tasa de inversion en infraestructura', 'Tasa de inversion en infraestructura', '',0,0),
(43, 2, 'Tasa de obras fiscalizadas', 'Tasa de obras fiscalizadas', '',0,0),
(44, 2, 'Tasa de quejas de usuarios', 'Tasa de quejas de usuarios', '',0,0),
(45, 2, 'Tasa de recaudación', 'Tasa de recaudación', '',0,0),
(46, 2, 'Tasa de satisfacción de autoridades de transporte', 'Tasa de satisfacción de autoridades de transporte', '',0,0),
(47, 2, 'Tasa de viajes en transporte', 'Tasa de viajes en transporte', '',0,0),
(48, 2, 'Total de Regulaciones viales', 'Total de Regulaciones viales', '',0,0),
(49, 3, 'Congestión vehicular', 'Congestión vehicular', '',0,0),
(50, 3, 'Estratégicas de ejecución de obras', 'Estratégicas de ejecución de obras', '',0,0),
(51, 3, 'Estres de transportistas', 'Estres de transportistas', '',0,0),
(52, 3, 'Extorsionesa a transportistas', 'Extorsionesa a transportistas', '',0,0),
(53, 3, 'Fluidez del tráfico', 'Fluidez del tráfico', '',0,0),
(54, 3, 'Infraestructural vial', 'Infraestructural vial', '',0,0),
(55, 3, 'Nivel de educacion vial', 'Nivel de educacion vial', '',0,0),
(56, 3, 'Nivel de satisfacción del usuario', 'Nivel de satisfacción del usuario', '',0,0),
(57, 3, 'Tasa de accidentes de transporte', 'Tasa de accidentes de transporte', '',0,0),
(58, 3, 'Tasa de conductores que consumen alcohol', 'Tasa de conductores que consumen alcohol', '',0,0),
(59, 3, 'Tasa de educacion vial de calidad', 'Tasa de educacion vial de calidad', '',0,0),
(60, 3, 'Tasa de extorsiones a transportistas', 'Tasa de extorsiones a transportistas', '',0,0),
(61, 3, 'Tasa de inversion en mantener estado optimo de vehiculos', 'Tasa de inversion en mantener estado optimo de vehiculos', '',0,0),
(62, 3, 'Tasa de pagos ilicitos en construcción vial', 'Tasa de pagos ilicitos en construcción vial', '',0,0),
(63, 3, 'Tasa de satisfacción del usuario', 'Tasa de satisfacción del usuario', '',0,0),
(64, 3, 'Tasa de seguridad en transportes', 'Tasa de seguridad en transportes', '',0,0),
(65, 3, 'Total de accidentes de transporte', 'Total de accidentes de transporte', '',0,0),
(66, 3, 'Total de conductores con consumo de alcohol', 'Total de conductores con consumo de alcohol', '',0,0),
(67, 3, 'Total de vehiculos de transporte público en buen estado', 'Total de vehiculos de transporte público en buen estado', '',0,0),
(68, 3, 'Total de vehiculos en buen estado', 'Total de vehiculos en buen estado', '',0,0),
(69, 3, 'Uso del transporte público', 'Uso del transporte público', '',0,0),
(70, 4, 'Congestión vehicular', 'Congestión vehicular', '',0,0),
(71, 4, 'Cumplimiento de las normas de transito', 'Cumplimiento de las normas de transito', '',0,0),
(72, 4, 'Educación vial', 'Educación vial', '',0,0),
(73, 4, 'Estres de transportistas', 'Estres de transportistas', '',0,0),
(74, 4, 'Extorsiones a transportistas', 'Extorsiones a transportistas', '',0,0),
(75, 4, 'Fiscalización y control policial', 'Fiscalización y control policial', '',0,0),
(76, 4, 'Infraestructura vial', 'Infraestructura vial', '',0,0),
(77, 4, 'Numero de accidentes de transito', 'Numero de accidentes de transito', '',0,0),
(78, 4, 'Paradas no autorizadas', 'Paradas no autorizadas', '',0,0),
(79, 4, 'Porcentaje de población con educacion vial', 'Porcentaje de población con educacion vial', '',0,0),
(80, 4, 'Señales correctamente establecidas', 'Señales correctamente establecidas', '',0,0),
(81, 4, 'Tasa de accidentes de transito', 'Tasa de accidentes de transito', '',0,0),
(82, 4, 'Tasa de conductores que consumen alcohol', 'Tasa de conductores que consumen alcohol', '',0,0),
(83, 4, 'Tasa de extorsiones a transportistas', 'Tasa de extorsiones a transportistas', '',0,0),
(84, 4, 'Tasa de fallas mecanicas en vehiculos', 'Tasa de fallas mecanicas en vehiculos', '',0,0),
(85, 4, 'Tasa de inversion en mantener estado optimo de vehiculos', 'Tasa de inversion en mantener estado optimo de vehiculos', '',0,0),
(86, 4, 'Tasa de obras de construccion vial fiscalizadas', 'Tasa de obras de construccion vial fiscalizadas', '',0,0),
(87, 4, 'Tasa de pagos ilicitos en construcción vial', 'Tasa de pagos ilicitos en construcción vial', '',0,0),
(88, 4, 'Tasa de Seguridad', 'Tasa de Seguridad', '',0,0),
(89, 4, 'Tasa de señales correctas', 'Tasa de señales correctas', '',0,0),
(90, 4, 'Tasa de Transporte informal', 'Tasa de Transporte informal', '',0,0),
(91, 4, 'Total de conductores con consumo de alcohol', 'Total de conductores con consumo de alcohol', '',0,0),
(92, 4, 'Total de vehiculos de transporte público en buen estado', 'Total de vehiculos de transporte público en buen estado', '',0,0),
(93, 5, 'Calidad de infraestructura vial', 'Calidad de infraestructura vial', '',0,0),
(94, 5, 'Calidad de transporte público', 'Calidad de transporte público', '',0,0),
(95, 5, 'Cantidad de Transporte informal', 'Cantidad de Transporte informal', '',0,0),
(96, 5, 'Congestión vehicular', 'Congestión vehicular', '',0,0),
(97, 5, 'Cruces de pistas indevidas por transeuntes', 'Cruces de pistas indevidas por transeuntes', '',0,0),
(98, 5, 'Eficiencia de movilidad', 'Eficiencia de movilidad', '',0,0),
(99, 5, 'Estratégicas de ejecución de obras', 'Estratégicas de ejecución de obras', '',0,0),
(100, 5, 'Estres de transportistas', 'Estres de transportistas', '',0,0),
(101, 5, 'Extorsionesa a transportistas', 'Extorsionesa a transportistas', '',0,0),
(102, 5, 'Fluidez del tráfico', 'Fluidez del tráfico', '',0,0),
(103, 5, 'Nivel de educación vial', 'Nivel de educación vial', '',0,0),
(104, 5, 'Número de vehículos en circulación', 'Número de vehículos en circulación', '',0,0),
(105, 5, 'Paradas no autorizadas utilizadas por vehiculo', 'Paradas no autorizadas utilizadas por vehiculo', '',0,0),
(106, 5, 'Póliticas de regulación de transporte', 'Póliticas de regulación de transporte', '',0,0),
(107, 5, 'Seguridad', 'Seguridad', '',0,0),
(108, 5, 'Tasa de educacion vial de calidad', 'Tasa de educacion vial de calidad  ', '',0,0),
(109, 5, 'Tasa de extorsiones a transportistas', 'Tasa de extorsiones a transportistas', '',0,0),
(110, 5, 'Tasa de infracciones', 'Tasa de infracciones', '',0,0),
(111, 5, 'Tasa de inversion de infraestructura', 'Tasa de inversion de infraestructura', '',0,0),
(112, 5, 'Tasa de población que utiliza aplicaciones de transporte', 'Tasa de población que utiliza aplicaciones de transporte', '',0,0),
(113, 5, 'Tasa de presión de pasajeros recibidas por conductores', 'Tasa de presión de pasajeros recibidas por conductores', '',0,0),
(114, 5, 'Tasa de seguridad', 'Tasa de seguridad', '',0,0),
(115, 5, 'Tasa de transeuntes que cruzan indevidamente', 'Tasa de transeuntes que cruzan indevidamente', '',0,0),
(116, 5, 'Tasa de transportes públicos en correcto estado', 'Tasa de transportes públicos en correcto estado', '',0,0),
(117, 5, 'Tasa de vehiculos en circulación', 'Total de conductores con consumo de alcohol', '',0,0),
(118, 5, 'Total de Infracciones', 'Total de Infracciones', '',0,0),
(119, 5, 'Uso de aplicaciones de transporte', 'Uso de aplicaciones de transporte', '',0,0),
(120, 5, 'Uso del transporte público', 'Uso del transporte público', '',0,0);


INSERT IGNORE INTO ConexionCausal (idCausal, idOrigen, idDestino, polaridad, color, x_curve, y_curve) VALUES
(1, 13, 10, '-','#FF0000', 45, 0),
(1, 10, 12, '+','#0000FF', 43, 0),
(1, 12, 13, '+','#0000FF', 43, 0),
(1,  9, 13, '+','#0000FF', 43, 0),
(1,  9, 12, '+','#0000FF', 43, 0),
(1,  8,  9, '+','#0000FF', 43, 0),
(1, 18,  9, '+','#0000FF', 43, 0),
(1, 18, 23, '-','#FF0000', 45, 0),
(1,  8, 23, '-','#FF0000', 45, 0),
(1, 23, 15, '+','#0000FF', 43, 0),
(1, 10, 15, '+','#0000FF', 43, 0),
(1, 15, 11, '+','#0000FF', 43, 0),
(1, 10,  5, '+','#0000FF', 43, 0),
(1,  5, 17, '+','#0000FF', 43, 0),
(1, 17, 11, '+','#0000FF', 43, 0),
(1, 17, 22, '-','#FF0000', 45, 0),
(1, 22, 19, '+','#0000FF', 43, 0),
(1, 19,  1, '+','#0000FF', 43, 0),
(1,  1,  4, '+','#0000FF', 43, 0),
(1,  4, 25, '-','#FF0000', 45, 0),
(1, 24, 16, '+','#0000FF', 43, 0),
(1, 24,  4, '+','#0000FF', 43, 0),
(1, 16,  4, '+','#0000FF', 43, 0),
(1, 25, 14, '+','#0000FF', 43, 0),
(1, 14,  2, '+','#0000FF', 43, 0),
(1,  2,  7, '+','#0000FF', 43, 0),
(1,  7,  6, '+','#0000FF', 43, 0),
(1, 15,  2, '-','#FF0000', 45, 0),
(1,  6, 22, '+','#0000FF', 43, 0),
(1, 11, 22, '-','#FF0000', 45, 0),
(1, 20, 21, '+','#0000FF', 43, 0),
(1, 20,  3, '+','#0000FF',  0, 0),
(1,  3, 23, '-','#FF0000', 45, 0),
(1,  3, 18, '+','#0000FF', 43, 0),
(1, 21, 13, '+','#0000FF', 43, 0),
(1, 20, 24, '-','#FF0000', 45, 0),
(1,  4, 19, '-','#FF0000', 45, 0),
(2,  32, 39, '+', '#0000FF', 43, 0),
(2,  48, 26, '-', '#FF0000', 45, 0),
(2,  26, 29, '-', '#FF0000', 45, 0),
(2,  29, 39, '+', '#0000FF', 43, 0),
(2,  37, 33, '-', '#FF0000', 45, 0),
(2,  33, 39, '+', '#0000FF', 43, 0),
(2,  32, 30, '-', '#FF0000', 45, 0),
(2,  30, 40, '-', '#FF0000', 45, 0),
(2,  40, 37, '-', '#FF0000', 45, 0),
(2,  40, 33, '+', '#0000FF', 43, 0),
(2,  35, 28, '+', '#0000FF', 43, 0),
(2,  28, 32, '+', '#0000FF', 43, 0),
(2,  31, 28, '+', '#0000FF', 43, 0),
(2,  28, 33, '+', '#0000FF', 43, 0),
(2,  28, 26, '-', '#FF0000', 45, 0),
(2,  31, 37, '-', '#FF0000', 45, 0),
(2,  37, 40, '-', '#FF0000', 45, 0),
(2,  38, 35, '+', '#0000FF',  43, 0),
(2,  43, 31, '', '#0000FF',  0, 0),
(2,  36, 38, '+', '#0000FF', 43, 0),
(2,  46, 39, '', '#0000FF',  0, 0),
(2,  41, 26, '', '#0000FF',  0, 0),
(2,  45, 38, '', '#0000FF',  0, 0),
(2,  42, 35, '', '#0000FF', 0, 0),
(2,  27, 31, '+', '#0000FF', 43, 0),
(2,  47, 36, '', '#0000FF',  0, 0),
(2,  44, 37, '', '#0000FF',  0, 0),
(2,  39, 33, '+', '#0000FF', 43, 0),
(2,  28, 35, '+', '#0000FF', 43, 0),
(2,  35, 38, '+', '#0000FF', 43, 0),
(2,  29, 26, '+', '#0000FF', 43, 0),
(2,  30, 34, '+', '#0000FF', 43, 0),
(2,  34, 36, '+', '#0000FF', 43, 0),
(2,  30, 40, '-', '#FF0000',  0, 0),
(3, 49, 56, '-', '#FF0000', 45, 0),
(3, 53, 56, '+', '#0000FF', 43, 0),
(3, 67, 69, '+', '#0000FF', 43, 0),
(3, 64, 52, '', '#0000FF',  0, 0),
(3, 51, 67, '-', '#FF0000', 45, 0),
(3, 54, 53, '+', '#0000FF', 43, 0),
(3, 54, 51, '+', '#0000FF', 43, 0),
(3, 50, 53, '+', '#0000FF', 43, 0),
(3, 69, 49, '+', '#0000FF', 45, 0),
(3, 56, 69, '+', '#0000FF', 43, 0),
(3, 55, 67, '+', '#0000FF', 43, 0),
(3, 55, 66, '-', '#FF0000', 45, 0),
(3, 66, 65, '+', '#0000FF', 43, 0),
(3, 65, 56, '+', '#0000FF', 45, 0),
(3, 52, 68, '-', '#FF0000', 45, 0),
(3, 68, 67, '+', '#0000FF', 43, 0),
(3, 67, 56, '+', '#0000FF', 43, 0),
(3, 64, 56, '', '#0000FF', 0, 0),
(3, 69, 53, '+', '#0000FF', 43, 0),
(3, 60, 52, '', '#0000FF',  0, 0),
(3, 61, 68, '', '#0000FF',  0, 0),
(3, 59, 55, '', '#0000FF',  0, 0),
(3, 63, 56, '', '#0000FF',  0, 0),
(3, 57, 65, '', '#0000FF',  0, 0),
(3, 58, 66, '', '#0000FF',  0, 0),
(3, 62, 54, '', '#0000FF',  0, 0),
(3, 68, 52, '+', '#0000FF', 43, 0),
(3, 65, 66, '+', '#0000FF', 43, 0),
(4, 76, 70, '-', '#FF0000', 45, 0),
(4, 70, 77, '+', '#0000FF', 43, 0),
(4, 72, 71, '+', '#0000FF', 43, 0),
(4, 71, 77, '-', '#FF0000', 45, 0),
(4, 75, 71, '+', '#0000FF', 43, 0),
(4, 90, 78, '', '#0000FF',  0, 0),
(4, 78, 70, '+', '#0000FF', 43, 0),
(4, 78, 77, '+', '#0000FF', 43, 0),
(4, 92, 77, '-', '#FF0000', 45, 0),
(4, 75, 91, '-', '#FF0000', 45, 0),
(4, 72, 91, '-', '#FF0000', 45, 0),
(4, 91, 77, '+', '#0000FF', 43, 0),
(4, 76, 80, '+', '#0000FF', 43, 0),
(4, 80, 77, '-', '#FF0000', 45, 0),
(4, 87, 76, '', '#FF0000',  0, 0),
(4, 75, 76, '-', '#FF0000', 45, 0),
(4, 74, 73, '+', '#0000FF', 43, 0),
(4, 74, 92, '-', '#FF0000', 45, 0),
(4, 88, 74, '', '#FF0000',  0, 0),
(4, 73, 77, '+', '#0000FF', 43, 0),
(4, 73, 91, '+', '#0000FF', 43, 0),
(4, 79, 72, '+', '#0000FF', 43, 0),
(4, 83, 74, '', '#0000FF',  0, 0),
(4, 86, 75, '', '#0000FF',  0, 0),
(4, 89, 80, '', '#0000FF', 0, 0),
(4, 81, 77, '', '#0000FF',  0, 0),
(4, 85, 92, '', '#0000FF',  0, 0),
(4, 84, 92, '', '#FF0000',  0, 0),
(4, 82, 91, '', '#0000FF',  0, 0),
(4, 77, 71, '+', '#0000FF',  0, 0),
(4, 73, 85, '+', '#0000FF',  0, 0),
(4, 70, 76, '+', '#0000FF', 43, 0),
(5,  96,  98, '-', '#FF0000', 45, 0),
(5, 102,  98, '+', '#0000FF', 43, 0),
(5, 120, 104, '-', '#FF0000', 45, 0),
(5, 104,  96, '+', '#0000FF', 43, 0),
(5,  94, 120, '+', '#0000FF', 43, 0),
(5, 118,  96, '+', '#0000FF', 43, 0),
(5,  95, 105, '+', '#0000FF', 43, 0),
(5, 105,  96, '+', '#0000FF', 43, 0),
(5, 103,  95, '-', '#FF0000', 45, 0),
(5, 103,  97, '-', '#FF0000', 45, 0),
(5,  97,  96, '+', '#0000FF', 43, 0),
(5, 113, 105, '', '#0000FF', 0, 0),
(5, 106,  95, '-', '#FF0000', 45, 0),
(5, 119, 120, '-', '#FF0000', 45, 0),
(5,  98, 119, '+', '#0000FF', 43, 0),
(5, 107, 119, '-', '#FF0000', 45, 0),
(5, 107, 101, '-', '#FF0000', 45, 0),
(5, 101, 100, '+', '#0000FF', 43, 0),
(5, 100,  94, '-', '#FF0000', 45, 0),
(5, 118, 100, '+', '#0000FF', 43, 0),
(5, 120, 119, '-', '#FF0000', 45, 0),
(5,  98,  96, '-', '#FF0000', 45, 0),
(5,  98, 102, '+', '#0000FF', 43, 0),
(5,  93, 102, '+', '#0000FF', 43, 0),
(5,  93, 100, '-', '#FF0000', 45, 0),
(5,  99, 102, '+', '#0000FF', 43, 0),
(5, 120, 102, '+', '#0000FF', 43, 0),
(5, 101, 107, '-', '#FF0000', 45, 0),
(5, 114, 107, '', '#0000FF',  0, 0),
(5, 110, 118, '', '#0000FF',  0, 0),
(5, 109, 101, '', '#0000FF',   0, 0),
(5, 115,  97, '', '#0000FF',   0, 0),
(5, 112, 119, '', '#0000FF',  0, 0),
(5, 111,  93, '', '#0000FF', 0, 0),
(5, 116,  94, '', '#0000FF', 0, 0),
(5, 117, 104, '', '#0000FF', 0, 0),
(5, 108, 103, '', '#0000FF',  0, 0),
(5, 113, 100, '', '#0000FF',  0, 0),
(5, 115, 100, '', '#0000FF',  0, 0);


CREATE TABLE IF NOT EXISTS SubModel (
  idSubmodel INT PRIMARY KEY,
  idForrester INT NOT NULL,
  nombre VARCHAR (500),
  UNIQUE (idForrester, nombre),
  FOREIGN KEY (idForrester) REFERENCES diagramaForrester (idForrester) ON DELETE CASCADE
);

INSERT IGNORE INTO SubModel (idSubmodel, idForrester, nombre) VALUES
(1, 1, "Disponibilidad de la flota"),
(2, 1, "Cantidad de vehiculos en operacion"),
(3, 1, "Cantidad de fallas mecanicas"),
(4, 1, "Disponibilidad de talleres"),
(5, 2, "Inversion en infraestructura"),
(6, 2, "Calidad de infraestructura vial"),
(7, 2, "Imagen pública de autoridades"),
(8, 2, "Confianza pública"),
(9, 2, "Accidentes de tránsito"),
(10, 3, "Total de vehiculos en buen estado"),
(11, 3, "Extorsiones a transportistas"),
(12, 3, "Total de vehiculos de transporte publico en buen estado"),
(13, 3, "Total de conductores con consumo de alcohol"),
(14, 3, "Total de accidentes de transporte"),
(15, 3, "Nivel de satisfaccion de usuarios"),
(16, 4, "Infraestructura de seguridad vial"),
(17, 4, "Infraestructura en mantenimiento"),
(18, 4, "Presupuesto mantenimiento de infraestructura"),
(19, 4, "Dispositivos viales operativos"),


INSERT IGNORE INTO variableForrester (idVariableForrester, idSubmodel, nombre, titulo, tipo, unidad, tiempo, x_pos, y_pos) VALUES
(1,1, "Disponibilidad de la flota", "Disponibilidad de la flota", "Stock", "Unidades", "Año", 0,0),
(2,1, "Vehiculos que regresan de mantenimiento", "Vehiculos que regresan de mantenimiento", "IFlow", "Unidades", "Año", 0,0),
(3,1, "Vehiculos que se retiran por mantenimiento", "Vehiculos que se retiran por mantenimiento", "OFlow", "Unidades", "Año", 0,0),
(4,1, "Vehiculos asignados a operar", "Vehiculos asignados a operar", "OFlow", "Unidades", "Año", 0,0),
(5,1, "Cantidad de vehiculos en mantenimiento", "Cantidad de vehiculos en mantenimiento", "Aux", "Unidades", "Año", 0,0),
(6,1, "Total de la flota", "Total de la flota", "Rate", "Unidades", "Año", 0,0),
(7,1, "Tasa de inoperatividad por fallas", "Tasa de inoperatividad por fallas", "Rate", "Unidades/año", "Año", 0,0),
(8,1, "Vehiculos operativos que mostraron fallas", "Vehiculos operativos que mostraron fallas", "Aux", "Unidades", "Año", 0,0),
(9,1, "Tasa de fallas mecanicas", "Tasa de fallas mecanicas", "Rate", "Fallas/año", "Año", 0,0),
(10,1, "Tasa de asignacion", "Tasa de asignacion", "Rate", "Unidades/año", "Año", 0,0),
(11,1, "Demanda de operacion", "Demanda de operacion", "Rate", "Unidades/año", "Año", 0,0),
(12,1, "Tiempo promedio de mantenimiento", "Tiempo promedio de mantenimiento", "Rate", "Horas/año", "Año", 0,0),
(13,1, "Error/Faltante1", "Error/Faltante", "Aux", "Unidades", "Año", 0,0),
(14,1, "Discrepancia1", "Discrepancia", "Aux", "Unidades", "Año", 0,0),
(15,1, "Objetivo1", "Objetivo", "Rate", "Horas/año", "Año", 0,0),

(16,2, "Cantidad de vehiculos en operacion", "Cantidad de vehiculos en operacion", "Stock", "Unidades", "Año", 0,0),
(17,2, "Vehiculos asignados a operar", "Vehiculos asignados a operar", "IFlow", "Unidades", "Año", 0,0),
(18,2, "Vehiculos devueltos al deposito", "Vehiculos devueltos al deposito", "OFlow", "Unidades", "Año", 0,0),
(19,2, "Tasa de asignacion", "Tasa de asignacion", "Rate", "Unidades/año", "Año", 0,0),
(20,2, "Demanda de operacion", "Demanda de operacion", "Rate", "Unidades/año", "Año", 0,0),
(21,2, "Tasa de retorno al deposito", "Tasa de retorno al deposito", "Rate", "Unidades/año", "Año", 0,0),
(22,2, "Tasa de retorno al deposito", "Tasa de retorno al deposito", "Rate", "Unidades/año", "Año", 0,0),
(23,2, "Error/Faltante3", "Error/Faltante", "Aux", "Unidades", "Año", 0,0),
(24,2, "Discrepancia3", "Discrepancia", "Aux", "Unidades", "Año", 0,0),
(25,2, "Objetivo3", "Objetivo", "Rate", "Horas/año", "Año", 0,0),

(26,3, "Cantidad de fallas mecanicas", "Cantidad de fallas mecanicas", "Stock", "Unidades", "Año", 0,0),
(27,3, "Numero de veces que ocurre una falla mecanica", "Numero de veces que ocurre una falla mecanica", "IFlow", "Unidades", "Año", 0,0),
(28,3, "Reparacion de fallas mecanicas", "Reparacion de fallas mecanicas", "OFlow", "Unidades", "Año", 0,0),
(29,3, "Cantidad de reparaciones preventivas", "Cantidad de reparaciones preventivas", "OFlow", "Unidades", "Año", 0,0),
(30,3, "Tasa de fallas mecanicas", "Tasa de fallas mecanicas", "Rate", "Fallas/año", "Año", 0,0),
(31,3, "Cantidad promedio de malas maniobras por vehiculo", "Cantidad promedio de malas maniobras por vehiculo", "Rate", "Unidades", "Año", 0,0),
(32,3, "Cantidad de malas maniobras", "Cantidad de malas maniobras", "Aux", "Unidades", "Año", 0,0),
(33,3, "Tasa de reparacion de fallas mecanicas", "Tasa de reparacion de fallas mecanicas", "Rate", "Fallas/año", "Año", 0,0),
(34,3, "Cantidad de vehiculos destinados a mantenimiento correctivo", "Cantidad de vehiculos destinados a mantenimiento correctivo", "Aux", "Unidades", "Año", 0,0),
(35,3, "Cantidad de vehiculos destinados a mantenimiento preventivo", "Cantidad de vehiculos destinados a mantenimiento preventivo", "Aux", "Unidades", "Año", 0,0),
(36,3, "Proporcion de vehiculos que van a mantenimiento correctivo", "Proporcion de vehiculos que van a mantenimiento correctivo", "Rate", "%", "Año", 0,0),
(37,3, "Tasa de reparaciones preventivas", "Tasa de reparaciones preventivas", "Rate", "Unidades/año", "Año", 0,0),
(38,3, "Error/Faltante2", "Error/Faltante", "Aux", "Unidades", "Año", 0,0),
(39,3, "Discrepancia2", "Discrepancia", "Aux", "Unidades", "Año", 0,0),
(40,3, "Objetivo2", "Objetivo", "Rate", "Horas/año", "Año", 0,0),

(41,4, "Disponibilidad de talleres", "Disponibilidad de talleres", "Stock", "Unidades", "Año", 0,0),
(42,4, "Cantidad de plazas sin asignacion de mantenimiento", "Cantidad de plazas sin asignacion de mantenimiento", "IFlow", "Unidades", "Año", 0,0),
(43,4, "Cantidad de plazas apartadas por mantenimiento", "Cantidad de plazas apartadas por mantenimiento", "OFlow", "Unidades", "Año", 0,0),
(44,4, "Demanda por mantenimiento", "Demanda por mantenimiento", "Aux", "Unidades", "Año", 0,0),
(45,4, "Capacidad de atencion por plaza", "Capacidad de atencion por plaza", "Rate", "Unidades", "Año", 0,0),
(46,4, "Total de plazas", "Total de plazas", "Rate", "Unidades", "Año", 0,0),
(47,4, "Cantidad de plazas ocupadas", "Cantidad de plazas ocupadas", "Aux", "Unidades/año", "Año", 0,0),
(48,4, "Tasa de liberacion de plazas", "Tasa de liberacion de plazas", "Aux", "Unidades/año", "Año", 0,0),
(49,4, "Cantidad de vehiculos que terminan el mantenimiento por semana", "Cantidad de vehiculos que terminan el mantenimiento por semana", "Rate", "Unidades", "Año", 0,0),
(50,4, "Error/Faltante4", "Error/Faltante", "Aux", "Unidades", "Año", 0,0),
(51,4, "Discrepancia4", "Discrepancia", "Aux", "Unidades", "Año", 0,0),
(52,4, "Objetivo4", "Objetivo", "Rate", "Horas/año", "Año", 0,0),

(53,5,"Inversion en infraestructura", "Inversion en infraestructura", "Stock", "Soles", "Año", 0, 0),
(54,5,"Flujo de inversion", "Flujo de inversion", "IFlow", "Soles", "Año", 0, 0),
(55,5,"Depreciacion de inversion", "Depreciacion de inversion", "OFlow", "Soles", "Año", 0, 0),
(56,5,"Porcentaje de inversion", "Porcentaje de inversion", "Rate", "%", "Año", 0, 0),
(57,5,"Tasa de recaudacion", "Tasa de recaudacion", "Rate", "Soles/Año", "Año", 0, 0),

(58,6,"Calidad de infraestructura vial", "Calidad de infraestructura vial", "Stock", "%", "Año", 0, 0),
(59,6,"Mejora de infraestructura", "Mejora de infraestructura", "IFlow", "%", "Año", 0, 0),
(60,6,"Deterioro de infraestructura", "Deterioro de infraestructura", "OFlow", "%", "Año", 0, 0),
(61,6,"Tasa de recaudacion", "Tasa de recaudacion", "Rate", "Soles/Año", "Año", 0, 0),
(62,6,"Congestion vehicular", "Congestion vehicular", "Aux", "%", "Año", 0, 0),
(63,6,"Total regulaciones viales", "Total regulaciones viales", "Aux", "Unidades", "Año", 0, 0),
(64,6,"Satisfaccion de usuarios", "Satisfaccion de usuarios", "Aux", "%", "Año", 0, 0),
(65,6,"Fluidez del trafico", "Fluidez del trafico", "Aux", "%", "Año", 0, 0),

(66,7,"Imagen pública de autoridades", "Imagen pública de autoridades", "Stock", "%", "Año", 0, 0),
(67,7,"Mejora de imagen", "Mejora de imagen", "IFlow", "%", "Año", 0, 0),
(68,7,"Deterioro de imagen", "Deterioro de imagen", "OFlow", "%", "Año", 0, 0),
(69,7,"Satisfaccion de autoridades de transporte", "Satisfaccion de autoridades de transporte", "Aux", "%", "Año", 0, 0),
(70,7,"Satisfaccion de usuarios", "Satisfaccion de usuarios", "Aux", "%", "Año", 0, 0),
(71,7,"Tasa de quejas de usuarios", "Tasa de quejas de usuarios", "Aux", "Quejas/año", "Año", 0, 0),
(72,7,"Quejas de usuarios", "Quejas de usuarios", "Aux", "Quejas", "Año", 0, 0),

(73,8,"Confianza pública", "Confianza pública", "Stock", "%", "Año", 0, 0),
(74,8,"Recuperacion de confianza", "Recuperacion de confianza", "IFlow", "%", "Año", 0, 0),
(75,8,"Perdida de confianza", "Perdida de confianza", "OFlow", "%", "Año", 0, 0),
(76,8,"Satisfaccion de usuarios", "Satisfaccion de usuarios", "Aux", "%", "Año", 0, 0),
(77,8,"Fluidez del trafico", "Fluidez del trafico", "Aux", "%", "Año", 0, 0),
(78,8,"Pagos de tributos de transporte", "Pagos de tributos de transporte", "Aux", "SOles", "Año", 0, 0),
(79,8,"Tasa de viajes de transporte", "Tasa de viajes de transporte", "Aux", "Viajes/año", "Año", 0, 0),
(80,8,"Satisfaccion de autoridades de transporte", "Satisfaccion de autoridades de transporte", "Aux", "%", "Año", 0, 0),


(81,9,"Accidentes de tránsito", "Accidentes de tránsito", "Stock", "Unidades", "Año", 0, 0),
(82,9,"Cantidad de accidentes", "Cantidad de accidentes", "IFlow", "Unidades", "Año", 0, 0),
(83,9,"Accidentes prevenidos", "Accidentes prevenidos", "OFlow", "Soles", "Año", 0, 0),
(84,9,"Congestion vehicular", "Congestion vehicular", "Aux", "%", "Año", 0, 0),
(85,9,"Fluidez del trafico", "Fluidez del trafico", "Aux", "%", "Año", 0, 0),
(86,9,"Total regulaciones viales", "Total regulaciones viales", "Aux", "Unidades", "Año", 0, 0),
(87,9,"Infracciones vehiculares", "Infracciones vehiculares", "Aux", "Unidades", "Año", 0, 0),





(88,10,"Total de vehiculos en buen estado", "Total de vehiculos en buen estado", "Stock", "Unidades", "Año", 0, 0),
(89,10,"Vehiculos en buen estado", "Vehiculos en buen estado", "IFlow", "Unidades", "Año", 0, 0),
(90,10,"Vehiculos descompuestos", "Vehiculos descompuestos", "OFlow", "Unidades", "Año", 0, 0),
(91,10,"Tasa de inversion de mantener los vehiculos en buen estado", "Tasa de inversion de mantener los vehiculos en buen estado", "Rate", "Vehiculos/año", "Año", 0, 0),
(92,10,"Uso del transporte publico", "Uso del transporte publico", "Aux", "%", "Año", 0, 0),

(88,11,"Extorsiones a transportistas", "Extorsiones a transportistas", "Stock", "Cantidad", "Año", 0, 0),
(89,11,"Extorsiones ocurridas", "Extorsiones ocurridas", "IFlow", "Cantidad", "Año", 0, 0),
(90,11,"Casos resueltos", "Casos resueltos", "OFlow", "Cantidad", "Año", 0, 0),
(91,11,"Tasa de extorsiones a transportistas", "Tasa de extorsiones a transportistas", "Rate", "Veces/año", "Año", 0, 0),
(92,11,"Tasa de seguridad en transportes", "Tasa de seguridad en transportes", "Rate", "Unidades/año", "Año", 0, 0),
(93,11,"Estres a transportistas", "Estres a transportistas", "Aux", "%", "Año", 0, 0),

(94,12,"Total de vehiculos de transporte publico en buen estado", "Total de vehiculos de transporte publico en buen estado", "Stock", "Cantidad", "Año", 0, 0),
(95,12,"Vehiculos de transporte publico en buen estado", "Vehiculos de transporte publico en buen estado", "IFlow", "Unidades", "Año", 0, 0),
(96,12,"Vehiculos de transporte en mal estado", "Vehiculos de transporte en mal estado", "OFlow", "Unidades", "Año", 0, 0),
(97,12,"Estres a transportistas", "Estres a transportistas", "Aux", "%", "Año", 0, 0),
(98,12,"Uso del transporte publico", "Uso del transporte publico", "Aux", "%", "Año", 0, 0),
(99,12,"Tasa de educacion vial", "Tasa de educacion vial", "Rate", "Personas/año", "Año", 0, 0),
(100,12,"Nivel de educación vial", "Nivel de educación vial", "Aux", "%", "Año", 0, 0),

(101,13,"Total de conductores con consumo de alcohol", "Total de conductores con consumo de alcohol", "Stock", "Unidades", "Año", 0, 0),
(102,13,"Conductores consumidores de alcohol", "Conductores consumidores de alcohol", "IFlow", "Unidades", "Año", 0, 0),
(103,13,"Conductores que dejan de consumir alcohol", "Conductores que dejan de consumir alcohol", "OFlow", "Unidades", "Año", 0, 0),
(104,13,"Tasa de conductores que consumen alcohol", "Tasa de conductores que consumen alcohol", "Rate", "Conductores/año", "Año", 0, 0),
(105,13,"Tasa de educacion vial", "Tasa de educacion vial", "Rate", "Personas/año", "Año", 0, 0),
(106,13,"Nivel de educación vial", "Nivel de educación vial", "Aux", "%", "Año", 0, 0),

(107,14,"Total de accidentes de transporte", "Total de accidentes de transporte", "Stock", "Unidades", "Año", 0, 0),
(108,14,"Nuevos accidentes", "Nuevos accidentes", "IFlow", "Unidades", "Año", 0, 0),
(109,14,"Accidentes antiguos", "Accidentes antiguos", "OFlow", "Unidades", "Año", 0, 0),
(110,14,"Tasa de accidentes de transporte", "Tasa de accidentes de transporte", "Rate", "Veces/año", "Año", 0, 0),

(111,15,"Nivel de satisfaccion de usuarios", "Nivel de satisfaccion de usuarios", "Stock", "%", "Año", 0, 0),
(112,15,"Satisfaccion de usuarios", "Satisfaccion de usuarios", "IFlow", "%", "Año", 0, 0),
(113,15,"Insatisfaccion de usuarios", "Insatisfaccion de usuarios", "OFlow", "%", "Año", 0, 0),
(114,15,"Tasas de pagos ilicitos en construcción vial", "Tasa de pagos ilicitos en construcción vial", "Rate", "Soles/año", "Año", 0, 0),
(115,15,"Tasa de satisfaccion de usuarios", "Tasa de satisfaccion de usuarios", "Rate", "%", "Año", 0, 0),
(116,15,"Estrategias de ejecucion de obras", "Cantidad de estrategias de ejecucion de obras", "Rate", "%", "Año", 0, 0),
(117,15,"Infraestructura vial", "Infraestructura vial", "Aux", "%", "Año", 0, 0),
(118,15,"Fluidez del trafico", "Fluidez del trafico", "Aux", "%", "Año", 0, 0),
(119,15,"Congestion vehicular", "Congestion vehicular ", "Aux", "%", "Año", 0, 0),

(120,16,"Infraestructura de seguridad vial", "Infraestructura de seguridad vial", "Stock", "%", "Año", 0, 0),
(121,16,"Infraestructura de seguridad vial en ejecución", "Infraestructura de seguridad vial en ejecución", "IFlow", "%", "Año", 0, 0),
(122,16,"Infraestructura de seguridad vial obsoleta", "Infraestructura de seguridad vial obsoleta", "OFlow", "%", "Año", 0, 0),
(123,16,"Tasa Ejecucion Seguridad Vial", "Tasa Ejecucion Seguridad Vial", "Rate", "Veces/año", "Año", 0, 0),
(124,16,"Tasa Infraestructura Seguridad Vial Obsoletas", "Tasa Infraestructura Seguridad Vial Obsoletas", "Rate", "%", "Año", 0, 0),
(125,16,"Servicios tecnicos para seguridad vial", "Servicios tecnicos para seguridad vial", "Aux", "Cantidad", "Año", 0, 0),
(126,16,"Equipamiento vial adquirida", "Equipamiento vial adquirida", "Aux", "Cantidad", "Año", 0, 0),
(127,16,"Gastos Totales Infraestructura seguridad vial", "Gastos Totales Infraestructura seguridad vial", "Aux", "Soles", "Año", 0, 0),

(128,17,"Infraestructura en mantenimiento", "Infraestructura en mantenimiento", "Stock", "Cantidad", "Año", 0, 0),
(129,17,"Secciones retiradas para mantenimiento", "Secciones retiradas para mantenimiento", "IFlow", "Cantidad", "Año", 0, 0),
(130,17,"Secciones reparadas", "Secciones reparadas", "OFlow", "Cantidad", "Año", 0, 0),
(131,17,"Tasa de mantenimiento correctivo seguridad", "Tasa de mantenimiento correctivo seguridad", "Rate", "Veces/año", "Año", 0, 0),
(132,17,"Tasa de reparación de infraestructura seguridad", "Tasa de reparación de infraestructura seguridad", "Rate", "Veces/año", "Año", 0, 0),

(133,18,"Presupuesto mantenimiento de infraestructura", "Presupuesto mantenimiento de infraestructura", "Stock", "Soles", "Año", 0, 0),
(134,18,"Fondos asignados para mantenimiento", "Fondos asignados para mantenimiento", "IFlow", "Soles", "Año", 0, 0),
(135,18,"Gastos en mantenimiento", "Gastos en mantenimiento", "OFlow", "Soles", "Año", 0, 0),
(136,18,"Tasa de mantenimiento infraestructura", "Tasa de mantenimiento infraestructura", "Rate", "Veces/año", "Año", 0, 0),
(137,18,"Costo promedio mantenimiento infraestructura", "Costo promedio mantenimiento infraestructura", "Rate", "Soles/año", "Año", 0, 0),

(138,19,"Dispositivos viales operativos", "Dispositivos viales operativos", "Stock", "Unidades", "Año", 0, 0),
(139,19,"Dispositivos de seguridad vial instalados nuevos", "Dispositivos de seguridad vial instalados nuevos", "IFlow", "Unidades", "Año", 0, 0),
(140,19,"Dispositivos de seguridad vial retirados por falla", "Dispositivos de seguridad vial retirados por falla", "OFlow", "Unidades", "Año", 0, 0),
(141,19,"Tasa de instalación de nuevos dispositivos", "Tasa de instalación de nuevos dispositivos", "Rate", "Veces/año", "Año", 0, 0),
(142,19,"Tasa de retiro de dispositivos por falla", "Tasa de retiro de dispositivos por falla", "Rate", "Veces/año", "Año", 0, 0),



